apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: prometheus-exporter-probe-http-kubernetes-io
spec:
  module: http_2xx
  prober:
    url: prometheus-exporter-probe-example-blackbox.prometheus-demo.svc:9115
  targets:
    staticConfig:
      static:
      - https://hello-world-prometheus-demo.apps.hubcluster-02.clustership.com
