---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prometheus-demo

commonAnnotations:
  argocd.argoproj.io/sync-wave: "10"

commonLabels:
  prometheus-demo: ""

resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- route.yaml
- service-monitor.yaml

#images:
#- name: quay.io/xymox/hello-prometheus
#  newTag: 0.0.1
