---
apiVersion: v1
kind: Service
metadata:
  name: hello-world
  namespace: prometheus-demo
  labels:
    app: hello-world
spec:
  type: ClusterIP  
  ports:
  - name: http-port
    port: 9999
    targetPort: http-port
  selector:
    app: hello-world
