apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: hello-world-prometheus-monitor
  name: hello-world-prometheus-monitor
  namespace: prometheus-demo
spec:
  endpoints:
  - interval: 15s
    port: http
    scheme: http
  selector:
    matchLabels:
      app: hello-world
